import CREATE_CHECK_WORDS_BUTONS from '../../training/view/checkWordsButtons';
import CREATE_CONTROLS_BAR_BUTTONS from '../../training/view/conrtolsBarButtons';

export default function showCard() {
  document.querySelector('.main-container').innerHTML = '';
  const wrapperCard = document.createElement('div');
  wrapperCard.classList = 'wrapper-card';
  document.querySelector('.main-container').append(wrapperCard);
  CREATE_CONTROLS_BAR_BUTTONS(wrapperCard);
  const card = document.createElement('div');
  card.classList = 'card';
  wrapperCard.append(card);
  const wordTranslate = document.createElement('p');
  wordTranslate.classList = 'word-translate';
  card.append(wordTranslate);
  const transcription = document.createElement('p');
  transcription.classList = 'word-transcription';
  card.append(transcription);
  const imageWord = document.createElement('img');
  imageWord.classList = 'image-word';
  card.append(imageWord);
  const form = document.createElement('form');
  form.id = 'form';
  form.classList = 'form';
  card.append(form);
  const containerContext = document.createElement('p');
  containerContext.classList = 'container-context';
  form.append(containerContext);
  const wordStart = document.createElement('span');
  wordStart.classList = 'word-start';
  containerContext.append(wordStart);
  const inputContainer = document.createElement('span');
  inputContainer.classList = 'input-container';
  containerContext.append(inputContainer);
  const inputBackground = document.createElement('span');
  inputBackground.classList = 'input-background';
  inputContainer.append(inputBackground);
  const writeWord = document.createElement('input');
  writeWord.classList = 'write-word';
  inputContainer.append(writeWord);
  const wordEnd = document.createElement('span');
  wordEnd.classList = 'word-end';
  containerContext.append(wordEnd);
  const showWord = document.createElement('p');
  showWord.classList = 'show-word';
  card.append(showWord);
  const textMeaning = document.createElement('p');
  textMeaning.classList = 'text-meaning';
  card.append(textMeaning);
  const textMeaningTranslate = document.createElement('p');
  textMeaningTranslate.classList = 'text-meaning-translate';
  card.append(textMeaningTranslate);
  CREATE_CHECK_WORDS_BUTONS(wrapperCard);
}
