export const MAIN_CONTAINER = document.querySelector('.main-container');

export const showForm = () => {
  const form = document.createElement('form');
  form.id = 'authorization';
  MAIN_CONTAINER.append(form);
  const inputSignIn = document.createElement('input');
  inputSignIn.checked = '0';
  inputSignIn.id = 'signin';
  inputSignIn.name = 'action';
  inputSignIn.type = 'radio';
  form.append(inputSignIn);
  const labelSignIn = document.createElement('label');
  labelSignIn.htmlFor = 'signin';
  labelSignIn.innerText = 'Sign in';
  form.append(labelSignIn);
  const inputSignUp = document.createElement('input');
  inputSignUp.id = 'signup';
  inputSignUp.name = 'action';
  inputSignUp.type = 'radio';
  form.append(inputSignUp);
  const labelSignUp = document.createElement('label');
  labelSignUp.htmlFor = 'signup';
  labelSignUp.innerText = 'Sign up';
  form.append(labelSignUp);
  const wrapper = document.createElement('div');
  wrapper.id = 'wrapper';
  form.append(wrapper);
  const arrow = document.createElement('div');
  arrow.id = 'arrow';
  wrapper.append(arrow);
  const inputEmail = document.createElement('input');
  inputEmail.type = 'email';
  inputEmail.id = 'email';
  inputEmail.placeholder = 'Enter email';
  inputEmail.pattern = '[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,}$';
  inputEmail.required = 'required';
  wrapper.append(inputEmail);
  const inputPassword = document.createElement('input');
  inputPassword.type = 'password';
  inputPassword.id = 'password';
  inputPassword.placeholder = 'Enter password';
  inputPassword.pattern = '(?=.*?[A-Z])(?=(.*[a-z]){1,})(?=(.*[\\d]){1,})(?=(.*[\\W]){1,})(?!.*\\s).{8,}';
  inputPassword.title = 'A form with a password field that must contain 8 or more characters that are of at least one number, and one uppercase and lowercase letter,one special character from: +-_@$!%*?&#.,;:[]{}';
  inputPassword.required = 'required';
  wrapper.append(inputPassword);
  const button = document.createElement('button');
  button.type = 'submit';
  button.className = 'button-sign';
  const spanIn = document.createElement('span');
  spanIn.innerText = 'Sign In';
  button.append(spanIn);
  const spanUp = document.createElement('span');
  spanUp.innerText = 'Sign Up';
  button.append(spanUp);
  form.append(button);
};
